<?php

namespace Vertilia\Data;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-01-29 at 21:38:51.
 * @coversDefaultClass Vertilia\Data\Record
 * @requires PHP 7
 */
class RecordTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers ::__constructor
     */
    public function testConstructor()
    {
        $record1 = new Record();
        $this->assertFalse(isset($record1->field_1));
        $record2 = new Record(['field1'=>'a', 'field2'=>'b']);
        $this->assertFalse(isset($record2->field_1));
        $record3 = new MyRecord();
        $this->assertFalse(isset($record3->field_1));
        $record4 = new MyRecord(['field_1'=>'a', 'field_2'=>'b']);
        $this->assertEquals('a', $record4->field_1);
        $this->assertEquals('b', $record4->field_2);
        $this->assertFalse(isset($record4->field_3));
    }

    /**
     * @covers ::setValues
     */
    public function testSetValues()
    {
        $record = new MyRecord();
        $this->assertEmpty($record->field_1);

        $record->setValues(['field1'=>'a', 'field2'=>'b']);
        $this->assertEquals('a', $record->field_1);
        $this->assertEquals('b', $record->field_2);
        $this->assertFalse(isset($record->field_3));
    }
}

class MyRecord extends Record
{
    public $field_1;
    public $field_2;
}
